[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NODE_VERSION = "18"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/about"
  to = "/about/index.html"
  status = 200

[[redirects]]
  from = "/hotels"
  to = "/hotels/index.html"
  status = 200

[[redirects]]
  from = "/scuba"
  to = "/scuba/index.html"
  status = 200

# Force HTTPS redirect
[[redirects]]
  from = "http://namaskarambharat.com/*"
  to = "https://namaskarambharat.com/:splat"
  status = 301
  force = true

[[redirects]]
  from = "http://www.namaskarambharat.com/*"
  to = "https://www.namaskarambharat.com/:splat"
  status = 301
  force = true

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Strict-Transport-Security = "max-age=31536000; includeSubDomains" 